// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYKfKiaWI7N_KywUkRVfTzjWDEkD4Zl8',
    appId: '1:67844522605:web:b6acda47880769208e7564',
    messagingSenderId: '67844522605',
    projectId: 'whatsapp-31c7b',
    authDomain: 'whatsapp-31c7b.firebaseapp.com',
    storageBucket: 'whatsapp-31c7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0n2BUQ8cd-t12yGowCcgXtBu3dBu54JY',
    appId: '1:67844522605:android:05f6bf9f1f6047fc8e7564',
    messagingSenderId: '67844522605',
    projectId: 'whatsapp-31c7b',
    storageBucket: 'whatsapp-31c7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFp69HwW_9JHSDV-u8lTTREiSvRgOjH8',
    appId: '1:67844522605:ios:fed35a65adce33638e7564',
    messagingSenderId: '67844522605',
    projectId: 'whatsapp-31c7b',
    storageBucket: 'whatsapp-31c7b.appspot.com',
    iosClientId: '67844522605-mg15iedfc001cko75cuo7h41unkoikf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
